#!/bin/bash
set -euo pipefail
# set -x

sudo su -c 'echo 655350 > /proc/sys/vm/max_map_count'
sudo cpupower frequency-set -g performance 2>/dev/null || true

VOLUME="mesh-artifact-data"

# default is for reproducible runs
RUN_COUNT='20'
SPEC_FLAGS=''
FIREFOX_ONLY='0'

RUN_FLAGS="--privileged --rm -t --mount type=volume,src=$VOLUME,dst=/data"

docker volume rm "$VOLUME" || true
docker volume create "$VOLUME" || true

TEST='1-redis'
echo "running $TEST"
docker run $RUN_FLAGS mwdsouza/mesh-artifact-$TEST ./test --runs $RUN_COUNT --data-dir=/data/$TEST frag --metric memory 

sudo rm -rf ./results-old
if [ -d ./results ]; then
    mv ./results ./results-old
fi
mkdir -p ./results

ANALYSIS_RUN="docker run $RUN_FLAGS --mount type=bind,src=$PWD/results,dst=/results --mount type=bind,src=$PWD/analysis,dst=/analysis,readonly mwdsouza/mesh-artifact-support "

$ANALYSIS_RUN sh -c 'cp -r /data/* /results/'

# docker sucks sometimes
sudo chown -R $USER results
