#!/bin/bash
set -euo pipefail
# set -x

sudo su -c 'echo 655350 > /proc/sys/vm/max_map_count'
sudo cpupower frequency-set -g performance 2>/dev/null || true

# so firefox is authorized to talk to X from within the containter
xhost local:root

VOLUME="mesh-artifact-data"

# default is for reproducible runs
RUN_COUNT='20'
SPEC_FLAGS=''
FIREFOX_ONLY='0'


while (( "$#" )); do
    if [[ '--getting-started' == "$1" ]]; then
        echo "Getting Started -- fewer runs"
        RUN_COUNT='2'
    else
        echo "unknown argument $1"
        exit 1
    fi
    shift
done

RUN_FLAGS="--privileged --rm -t --mount type=volume,src=$VOLUME,dst=/data" 

docker volume rm "$VOLUME" || true
docker volume create "$VOLUME" || true

FF_WAIT_SECS="$(head -n 1 firefox-wait-seconds)"

TEST='0-firefox'
echo "running $TEST ($RUN_COUNT)"
docker run $RUN_FLAGS --ipc=host -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY mwdsouza/mesh-artifact-0-firefox:latest ./entrypoint.sh $RUN_COUNT $FF_WAIT_SECS "memory"

# TEST='1-redis'
# echo "running $TEST"
# docker run $RUN_FLAGS bpowers/mesh-artifact-$TEST ./test --runs $RUN_COUNT --data-dir=/data/$TEST
# 
# TEST='2-spec'
# echo "running $TEST"
# (cd 2-spec/runner && ./test $SPEC_FLAGS --volume=$VOLUME)
# 
# TEST='3-ruby'
# echo "running $TEST"
# docker run $RUN_FLAGS bpowers/mesh-artifact-$TEST ./test --runs $RUN_COUNT --data-dir=/data/$TEST


sudo rm -rf ./results-old
if [ -d ./results ]; then
    mv ./results ./results-old
fi
mkdir -p ./results

ANALYSIS_RUN="docker run $RUN_FLAGS --mount type=bind,src=$PWD/results,dst=/results --mount type=bind,src=$PWD/analysis,dst=/analysis,readonly mwdsouza/mesh-artifact-support "

$ANALYSIS_RUN sh -c 'cp -r /data/* /results/'

# docker sucks sometimes
sudo chown -R $USER results

# delete results for short-lived subprocesses firefox spawns
find results/0-firefox/memory -name '*.tsv' -size -10k -delete

./analysis/0-firefox.py
# ./analysis/1-redis.py
# ./analysis/2-spec.py
# ./analysis/3-ruby.py

(cd results/0-firefox/memory; rm -f jemalloc.tsv; ln -s $(ls -t speedometer.jemalloc*.tsv | sed -n '2p') jemalloc.tsv)
(cd results/0-firefox/memory; rm -f mesh.tsv; ln -s $(ls -t speedometer.mesh*.tsv | grep -v mesh_new | sed -n '2p') mesh.tsv)
(cd results/0-firefox/memory; rm -f mesh_new.tsv; ln -s $(ls -t speedometer.mesh_new*.tsv | sed -n '2p') mesh_new.tsv)

$ANALYSIS_RUN sh -c 'SOURCE_DATE_EPOCH=0 R --vanilla <analysis/figure-6-firefox.r'
# $ANALYSIS_RUN sh -c 'SOURCE_DATE_EPOCH=0 R --vanilla <analysis/figure-7-redis.r'
# $ANALYSIS_RUN sh -c 'SOURCE_DATE_EPOCH=0 R --vanilla <analysis/figure-8-ruby.r'
