#!/bin/bash

DATE=`date +%s.%N`
SUFFIX=`cat /dev/urandom | tr -cd 'a-f0-9' | head -c 8`

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

version=57.0.4
if [ "$TEST_NAME" = "jemalloc" ]; then
    binary=/opt/firefox-${version}-jemalloc/bin/firefox
else
    binary=/opt/firefox-${version}-nojemalloc/bin/firefox
fi

case $TEST_METRIC in
    "memory")
        if [ ! -z "$TEST_LD_PRELOAD" ]; then
            arg="-env LD_PRELOAD=$TEST_LD_PRELOAD"
        else
            arg=""
        fi
        mkdir -p /data/0-firefox/memory
        exec mstat -o "/data/0-firefox/memory/speedometer.$TEST_NAME.$DATE-$SUFFIX.tsv" $arg $binary "$@"
        ;;
    "speed")
        if [ ! -z "$TEST_LD_PRELOAD" ]; then
            LD_PRELOAD="$TEST_LD_PRELOAD" exec $binary "$@"
        else
            exec $binary "$@"
        fi
        ;;
    "cache")
        mkdir -p /data/0-firefox/cache
        outfile="/data/0-firefox/cache/speedometer.$TEST_NAME.$DATE-$SUFFIX.txt"
        exec perf stat -e dTLB-load-misses,iTLB-load-misses,dTLB-store-misses,cache-references,cache-misses -x' ' -o $outfile "$DIR/firefox-test-wrapper-perf" $binary "$@"
        ;;
    *)
        echo "Unrecognized metric $TEST_METRIC"
        exit 1
        ;;
esac
